import { Gift, ArrowRight } from "lucide-react";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const offers = [
  { title: "Business Bloom Prompt Starter Library", category: "Prompts", description: "A planned starter collection for common business-building tasks.", interest: "prompt-starter-library", action: "Get Early Access", next: "Business Bloom Engine" },
  { title: "Business Startup and Growth Checklist", category: "Planning", description: "A planned checklist for organizing startup and growth priorities.", interest: "startup-growth-checklist", action: "Request the Guide", next: "Business Bloom Engine" },
  { title: "Business Automation Starter Guide", category: "Automation", description: "A planned introduction to choosing practical, owner-supervised automations.", interest: "business-automation-guide", action: "Request the Guide", next: "Business Bloom Engine" },
  { title: "Funding Readiness Checklist", category: "Capital Preparation", description: "A planned general preparation checklist; credit and funding services belong to Business Bloom Capital.", interest: "funding-readiness-checklist", action: "Notify Me When Available", next: "Business Bloom Capital referral" },
  { title: "Funding Strategy Mini Playbook", category: "Capital Preparation", description: "A planned educational resource that will not promise approval or funding outcomes.", interest: "funding-strategy-playbook", action: "Join the Resource List", next: "Business Bloom Capital referral" },
  { title: "Five-Day Business Growth Email Challenge", category: "Growth", description: "A planned email challenge. Enrollment and automated delivery are not yet connected.", interest: "5-day-email-challenge", action: "Notify Me When Available", next: "Business Bloom Engine" },
  { title: "AI Agent Starter Guide", category: "AI Agents", description: "A planned guide to selecting and supervising AI agents responsibly.", interest: "ai-agent-starter-guide", action: "Get Early Access", next: "Agent Marketplace" },
];

export default function FreeStore() {
  return <div className="min-h-screen bg-[#0B0F1A] text-white"><NavBar /><section className="pt-32 pb-16 text-center px-4"><Gift className="h-12 w-12 text-[#14B8A6] mx-auto mb-6"/><p className="text-[#14B8A6] font-semibold mb-4">FREE STORE FOUNDATION</p><h1 className="text-4xl sm:text-6xl font-black mb-6">Free Resources Being Built for Entrepreneurs</h1><p className="text-white/60 text-xl max-w-3xl mx-auto">Join a resource interest list now. These planned assets are not immediate downloads, and automated delivery is not yet operational.</p></section><section className="max-w-7xl mx-auto px-4 pb-20 grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{offers.map(o => <article key={o.title} className="p-6 rounded-2xl bg-[#0D1120] border border-white/10 flex flex-col"><div className="aspect-[16/9] rounded-xl bg-gradient-to-br from-[#7C3AED]/20 to-[#14B8A6]/10 flex items-center justify-center mb-5"><Gift className="h-9 w-9 text-white/40"/><span className="sr-only">Product image placeholder</span></div><div className="flex justify-between gap-3 mb-3"><span className="text-[#14B8A6] text-xs font-semibold">{o.category}</span><span className="text-[#A78BFA] text-xs">Coming Soon</span></div><h2 className="text-xl font-bold mb-2">{o.title}</h2><p className="text-white/50 text-sm leading-relaxed mb-4">{o.description}</p><p className="text-white/40 text-xs mb-5">Relevant next step: {o.next}</p><a href={`/get-started?interest=${o.interest}`} className="mt-auto inline-flex items-center gap-2 text-[#14B8A6] font-semibold">{o.action}<ArrowRight className="h-4 w-4"/></a></article>)}</section><Footer /></div>;
}
