import { motion } from "framer-motion";
import { Rocket, Hammer, Megaphone, Settings, TrendingUp, Bot, Store, MessageSquare, ShoppingBag, Server, Globe, Landmark, ArrowRight } from "lucide-react";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const journey = [
  { icon: Rocket, title: "Start", text: "Shape the idea and organize the first decisions." },
  { icon: Hammer, title: "Build", text: "Create plans, messaging, systems, and operating foundations." },
  { icon: Megaphone, title: "Launch", text: "Prepare offers and customer-facing work for owner approval." },
  { icon: Settings, title: "Operate", text: "Document workflows and supervise practical automation." },
  { icon: TrendingUp, title: "Grow", text: "Review performance, identify opportunities, and choose next actions." },
  { icon: Landmark, title: "Connect", text: "Request a Business Bloom Capital referral when credit or funding support is appropriate." },
];
const ecosystem = [
  { icon: Bot, title: "Business Bloom Engine", text: "The AI-powered workspace for planning, creating, organizing, automating, and growing a business.", href: "https://app.businessbloomllc.com/", action: "Open the Engine", external: true },
  { icon: Store, title: "Agent Marketplace", text: "Explore specialized assistants, with honest access labels for Engine and upcoming agents.", href: "/marketplace", action: "Explore Marketplace" },
  { icon: MessageSquare, title: "Prompt Library", text: "Affordable entry products and implementation systems that support real business workflows.", href: "/prompt-packs", action: "Explore Prompts" },
  { icon: Store, title: "Free Store", text: "Join interest lists for planned guides, checklists, prompt resources, and challenges.", href: "/free-store", action: "Visit Free Store" },
  { icon: ShoppingBag, title: "Shopify App", text: "Explore the existing Shopify tools and plans for e-commerce operations.", href: "/shopify-app", action: "View Shopify App" },
  { icon: Server, title: "Hosting", text: "Business web-hosting options with existing checkout preserved.", href: "/hosting", action: "View Hosting" },
  { icon: Globe, title: "Domains", text: "Review domain options while verified registration remains temporarily unavailable.", href: "/domains", action: "View Domains" },
];

export default function Home() {
  return <div className="min-h-screen bg-[#0B0F1A] text-white"><NavBar />
    <section className="relative pt-32 pb-20 text-center px-4 overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(124,58,237,.15),transparent_40%),radial-gradient(circle_at_bottom_right,rgba(20,184,166,.12),transparent_35%)]"/><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="relative max-w-5xl mx-auto"><p className="text-[#14B8A6] font-semibold mb-5">ONE BUSINESS-BUILDING ECOSYSTEM</p><h1 className="text-4xl sm:text-6xl lg:text-7xl font-black leading-tight mb-7">Start, Build, Launch, Operate, and Grow with Business Bloom</h1><p className="text-xl text-white/60 max-w-3xl mx-auto mb-10">Business Bloom is an AI-powered business-building ecosystem. AI helps with drafting, organizing, analysis, automation, and production while you remain the owner and decision-maker.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><a href="https://app.businessbloomllc.com/" target="_blank" rel="noopener noreferrer" className="px-7 py-4 rounded-xl bg-[#7C3AED] font-bold">Open Business Bloom Engine</a><a href="/marketplace" className="px-7 py-4 rounded-xl border border-white/15 font-bold">Explore the Marketplace</a></div></motion.div></section>
    <section className="py-20 border-t border-white/5"><div className="max-w-7xl mx-auto px-4"><div className="text-center mb-12"><h2 className="text-3xl sm:text-4xl font-black mb-3">Your Business-Building Journey</h2><p className="text-white/60">Use AI for heavy lifting, then review, decide, approve, and execute.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{journey.map((s,i)=><motion.article key={s.title} initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}} className="p-6 rounded-2xl bg-[#0D1120] border border-white/10"><s.icon className="h-7 w-7 text-[#14B8A6] mb-4"/><p className="text-[#7C3AED] text-xs font-bold">STEP {i+1}</p><h3 className="text-xl font-bold mt-1 mb-2">{s.title}</h3><p className="text-white/50 text-sm">{s.text}</p></motion.article>)}</div></div></section>
    <section className="py-20 border-t border-white/5"><div className="max-w-7xl mx-auto px-4"><h2 className="text-3xl sm:text-4xl font-black text-center mb-12">Explore the Ecosystem</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{ecosystem.map(item=><article key={item.title} className="p-6 rounded-2xl bg-[#0D1120] border border-white/10"><item.icon className="h-7 w-7 text-[#7C3AED] mb-4"/><h3 className="text-xl font-bold mb-2">{item.title}</h3><p className="text-white/50 text-sm mb-5">{item.text}</p><a href={item.href} target={item.external ? "_blank" : undefined} rel={item.external ? "noopener noreferrer" : undefined} className="inline-flex items-center gap-2 text-[#14B8A6] font-semibold">{item.action}<ArrowRight className="h-4 w-4"/></a></article>)}</div></div></section>
    <section className="py-20 border-t border-white/5"><div className="max-w-4xl mx-auto px-4 text-center"><Landmark className="h-12 w-12 text-[#14B8A6] mx-auto mb-5"/><h2 className="text-3xl sm:text-4xl font-black mb-4">Need help with credit or business funding?</h2><p className="text-white/60 text-lg mb-4">Business Bloom Capital is the dedicated platform for credit readiness, funding preparation, and appropriate capital support. Business Bloom does not duplicate those services or guarantee approval.</p><p className="text-white/40 text-sm mb-7">The Capital destination URL is not yet confirmed, so this action records your interest rather than sending you to an unverified site.</p><a href="/get-started?interest=business-bloom-capital" className="inline-flex items-center gap-2 px-7 py-4 rounded-xl bg-[#14B8A6] font-bold">Request Funding and Credit Support<ArrowRight className="h-5 w-5"/></a></div></section><Footer /></div>;
}
