import { motion } from "framer-motion";
import { Bot, ArrowRight, BriefcaseBusiness } from "lucide-react";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const categories = ["Executive Leadership", "Marketing and Content", "Sales and Customer Service", "Finance and Operations", "Legal and Compliance", "Human Resources", "Technology and Automation", "Business Startup", "Funding Preparation", "Industry-Specific Agents"];

const agents = [
  { name: "Business Launch Guide", department: "Business Startup", description: "Organizes business ideas, launch priorities, and next steps for owner review.", problems: "Unclear launch plans and scattered decisions", assignments: "Draft a launch checklist or organize a business concept", capabilities: "Planning frameworks and structured worksheets", user: "New and early-stage entrepreneurs", access: "Available in the Engine", href: "https://app.businessbloomllc.com/" },
  { name: "Marketing Planner", department: "Marketing and Content", description: "Helps structure campaign ideas and content plans while the owner approves strategy and messaging.", problems: "Inconsistent planning and content direction", assignments: "Outline a campaign or build a content calendar", capabilities: "Planning, drafting, and organization", user: "Entrepreneurs and small teams", access: "Available in the Engine", href: "https://app.businessbloomllc.com/" },
  { name: "Operations Organizer", department: "Finance and Operations", description: "Turns repeatable work into draft processes, checklists, and operating plans.", problems: "Undocumented workflows and operational gaps", assignments: "Draft an SOP or map an onboarding workflow", capabilities: "Process mapping and document drafting", user: "Owners building repeatable operations", access: "Coming Soon", href: "/get-started?interest=operations-organizer-agent" },
  { name: "Funding Preparation Guide", department: "Funding Preparation", description: "Provides general organization support and refers credit or funding needs to Business Bloom Capital.", problems: "Unorganized preparation questions", assignments: "Create a document-gathering checklist", capabilities: "General preparation and referral only", user: "Owners exploring future capital support", access: "Coming Soon", href: "/get-started?interest=business-bloom-capital" },
];

export default function Marketplace() {
  return <div className="min-h-screen bg-[#0B0F1A] text-white"><NavBar />
    <section className="pt-32 pb-16 text-center px-4"><Bot className="h-12 w-12 text-[#14B8A6] mx-auto mb-6" /><p className="text-[#14B8A6] font-semibold mb-4">AGENT MARKETPLACE FOUNDATION</p><h1 className="text-4xl sm:text-6xl font-black mb-6">Find AI Support for the Work in Front of You</h1><p className="text-white/60 text-xl max-w-3xl mx-auto">Explore specialized assistants designed to help draft, organize, analyze, and plan. You remain responsible for decisions, approvals, relationships, and execution.</p></section>
    <section className="max-w-7xl mx-auto px-4 pb-12"><div className="flex flex-wrap justify-center gap-2">{categories.map(c => <span key={c} className="px-3 py-2 rounded-full border border-white/10 text-white/60 text-xs">{c}</span>)}</div></section>
    <section className="max-w-7xl mx-auto px-4 pb-20 grid md:grid-cols-2 gap-6">{agents.map((agent, i) => <motion.article key={agent.name} initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}} className="p-7 rounded-2xl bg-[#0D1120] border border-white/10"><div className="flex justify-between gap-4 mb-4"><div><p className="text-[#14B8A6] text-xs font-semibold">{agent.department}</p><h2 className="text-2xl font-bold mt-1">{agent.name}</h2></div><span className="h-fit px-3 py-1 rounded-full bg-[#7C3AED]/15 text-[#A78BFA] text-xs">{agent.access}</span></div><p className="text-white/60 mb-5">{agent.description}</p><dl className="space-y-3 text-sm"><div><dt className="text-white font-semibold">Problems solved</dt><dd className="text-white/50">{agent.problems}</dd></div><div><dt className="text-white font-semibold">Example assignments</dt><dd className="text-white/50">{agent.assignments}</dd></div><div><dt className="text-white font-semibold">Included capabilities</dt><dd className="text-white/50">{agent.capabilities}</dd></div><div><dt className="text-white font-semibold">Intended user</dt><dd className="text-white/50">{agent.user}</dd></div></dl><a href={agent.href} target={agent.href.startsWith("http") ? "_blank" : undefined} rel={agent.href.startsWith("http") ? "noopener noreferrer" : undefined} className="inline-flex items-center gap-2 mt-6 text-[#14B8A6] font-semibold">{agent.access === "Available in the Engine" ? "Open in the Engine" : "Join the Waitlist"}<ArrowRight className="h-4 w-4" /></a></motion.article>)}</section>
    <section className="border-t border-white/5 py-16 text-center px-4"><BriefcaseBusiness className="h-10 w-10 text-[#7C3AED] mx-auto mb-4"/><h2 className="text-3xl font-black mb-3">Need active business-building tools?</h2><p className="text-white/60 max-w-2xl mx-auto mb-6">The Business Bloom Engine is the AI-powered workspace for planning, creating, organizing, automating, and growing a business.</p><a href="https://app.businessbloomllc.com/" target="_blank" rel="noopener noreferrer" className="inline-flex px-6 py-3 rounded-xl bg-[#7C3AED] font-bold">Open Business Bloom Engine</a></section><Footer /></div>;
}
