import { ArrowRight, CheckCircle, MessageSquare, FileText, Brain } from "lucide-react";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { initiateCheckout } from "@/lib/checkout";
import { SERVICE_PRICES } from "../../../shared/servicePricing";

const ladder = ["Free Mini Prompt Packs: $0", "Individual Prompt Packs: $7–$17", "Advanced Workflow Packs: $27–$47", "Complete Prompt Library: $47–$67", "Prompt + SOP + Templates Systems: $67–$97"];
const products = [
  { title: "Sales and Closing System", description: "Existing Sales & Closing Pack Stripe mapping, repositioned as a workflow-focused entry system.", includes: ["Sales and closing prompt collection", "Objection and follow-up starting points", "Owner review and customization required"], priceKey: "PROMPT_STARTER" as const, icon: MessageSquare },
  { title: "Marketing Content System", description: "Existing Marketing & Content Pack Stripe mapping, framed around repeatable content workflows.", includes: ["Marketing and content prompt collection", "Campaign drafting starting points", "Owner approval remains required"], priceKey: "PROMPT_PRO" as const, icon: FileText },
  { title: "AI Business Implementation Kit", description: "Existing Complete Business Bundle Stripe mapping, repositioned as a broader implementation kit.", includes: ["Combined business prompt collection", "Cross-functional drafting support", "No autonomous business-operation claim"], priceKey: "PROMPT_ULTIMATE" as const, icon: Brain },
];

export default function PromptPacks() {
  const success = new URLSearchParams(window.location.search).get("success") === "true";
  return <div className="min-h-screen bg-[#0B0F1A] text-white"><NavBar />{success && <div className="fixed top-16 inset-x-0 z-40 bg-[#14B8A6]/20 py-3 text-center text-[#14B8A6]">Payment successful. Access and delivery timing depend on the existing fulfillment process.</div>}<section className="pt-32 pb-16 text-center px-4"><p className="text-[#14B8A6] font-semibold mb-4">PROMPTS, WORKFLOWS, AND IMPLEMENTATION SYSTEMS</p><h1 className="text-4xl sm:text-6xl font-black mb-6">Turn Better Instructions into Repeatable Business Work</h1><p className="text-white/60 text-xl max-w-3xl mx-auto">Start with affordable prompts, then move toward workflow packs, SOPs, templates, and implementation systems. AI output still requires your judgment and approval.</p></section><section className="max-w-5xl mx-auto px-4 pb-16"><div className="p-6 rounded-2xl bg-[#0D1120] border border-white/10"><h2 className="text-2xl font-bold mb-4">Approved Product Ladder</h2><div className="grid sm:grid-cols-2 gap-3">{ladder.map(l=><div key={l} className="flex gap-2 text-white/60 text-sm"><CheckCircle className="h-4 w-4 text-[#14B8A6] shrink-0"/>{l}</div>)}</div><p className="text-white/40 text-xs mt-5">The ladder is positioning guidance. Displayed checkout prices below remain tied to existing Stripe Price IDs and have not been changed.</p></div></section><section className="max-w-7xl mx-auto px-4 pb-20 grid lg:grid-cols-3 gap-6">{products.map(p=>{const configured=SERVICE_PRICES[p.priceKey];return <article key={p.title} className="p-7 rounded-2xl bg-[#0D1120] border border-white/10 flex flex-col"><p.icon className="h-8 w-8 text-[#7C3AED] mb-4"/><h2 className="text-2xl font-bold mb-2">{p.title}</h2><p className="text-white/50 text-sm mb-5">{p.description}</p><ul className="space-y-3 mb-6">{p.includes.map(i=><li key={i} className="flex gap-2 text-sm text-white/65"><CheckCircle className="h-4 w-4 text-[#14B8A6] shrink-0 mt-0.5"/>{i}</li>)}</ul><div className="mt-auto"><p className="text-3xl font-black text-[#14B8A6] mb-4">{configured.price}</p><button onClick={()=>initiateCheckout(configured.priceId,configured.name)} className="w-full inline-flex justify-center items-center gap-2 px-5 py-3 rounded-xl bg-[#7C3AED] font-bold">Continue to Checkout<ArrowRight className="h-4 w-4"/></button></div></article>})}</section><section className="py-16 border-t border-white/5 text-center px-4"><h2 className="text-3xl font-black mb-3">Looking for a free starting point?</h2><p className="text-white/60 mb-6">Join the early-access list for the planned Prompt Starter Library.</p><a href="/get-started?interest=prompt-starter-library" className="inline-flex px-6 py-3 rounded-xl border border-[#14B8A6]/30 text-[#14B8A6] font-bold">Get Early Access</a></section><Footer /></div>;
}
