import { CreditCard, Download, Gift, HelpCircle, KeyRound, Mail, Rocket, ShoppingBag } from "lucide-react";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const supportAreas = [
  { icon: ShoppingBag, title: "Purchase help", text: "Include the product name and the email address used at checkout so Business Bloom can identify the purchase." },
  { icon: Download, title: "Download help", text: "Tell us which product or Free Resource you expected, whether the delivery email arrived, and what happens when you use the download link." },
  { icon: KeyRound, title: "Access help", text: "Include the product name, checkout email, and the exact access step or error you see. Never send a password or secret credential." },
  { icon: Rocket, title: "Onboarding help", text: "Tell us which onboarding instruction or next-step link is unclear or unavailable so support can route you correctly." },
  { icon: CreditCard, title: "Billing & checkout help", text: "Include the product name, checkout email, and a concise description of the payment or checkout issue. Never send a full card number." },
  { icon: Gift, title: "Free Resource help", text: "Include the resource name and describe whether the issue is downloading, opening, editing, or using the file." },
];

export default function Support() {
  return <div className="min-h-screen bg-[#0B0F1A] text-white overflow-x-hidden"><NavBar /><main className="pt-28 pb-20"><section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-[#14B8A6] text-sm font-bold uppercase tracking-wider">Business Bloom Support</p><h1 className="mt-4 text-4xl sm:text-5xl font-black">Clear help for purchases, downloads, access, onboarding, and Free Resources.</h1><p className="mt-6 text-lg text-white/60 leading-relaxed max-w-3xl">If something is unclear, contact Business Bloom Support and provide enough non-sensitive information for the team to identify the order, resource, or problem quickly.</p><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mt-12">{supportAreas.map((item) => <article key={item.title} className="p-6 rounded-2xl bg-[#0D1120] border border-white/10"><item.icon className="h-6 w-6 text-[#7C3AED]" /><h2 className="mt-4 text-lg font-bold">{item.title}</h2><p className="mt-3 text-sm text-white/55 leading-relaxed">{item.text}</p></article>)}</div><div className="grid lg:grid-cols-[1.2fr_1fr] gap-6 mt-12"><div className="p-7 rounded-2xl border border-white/10 bg-[#0D1120]"><div className="flex items-start gap-4"><Mail className="h-6 w-6 text-[#14B8A6] shrink-0" /><div><h2 className="text-xl font-bold">Contact Business Bloom</h2><p className="mt-2 text-white/60 leading-relaxed">Email <a href="mailto:support@businessbloomllc.com" className="text-[#14B8A6] font-semibold hover:underline">support@businessbloomllc.com</a> for purchase, delivery, access, onboarding, billing, privacy, Terms, licensing, or product-support questions. Include your checkout email when relevant, the exact product or resource name, and a concise description of the issue. Do not send passwords, full card numbers, API keys, authentication tokens, or other secrets.</p><a href="mailto:support@businessbloomllc.com" className="mt-5 inline-flex px-5 py-3 rounded-xl bg-[#7C3AED] font-bold">Email Support</a></div></div></div><div className="p-7 rounded-2xl border border-white/10 bg-[#0D1120]"><HelpCircle className="h-6 w-6 text-[#F59E0B]" /><h2 className="mt-4 text-xl font-bold">Before contacting support</h2><ul className="mt-4 space-y-3 text-sm text-white/60"><li>Check the email address used at checkout.</li><li>Review your delivery or access email for the approved next step.</li><li>Confirm the product or Free Resource name.</li><li>Keep a screenshot or exact error message if something fails.</li></ul></div></div><div className="mt-12 p-7 rounded-2xl border border-[#7C3AED]/25 bg-[#7C3AED]/8"><h2 className="text-xl font-bold">Support expectations</h2><p className="mt-3 text-white/60 leading-relaxed">Business Bloom Support can help identify purchase, delivery, access, onboarding, billing, and product-use issues. Questions requiring licensed legal, tax, accounting, HR, or other regulated professional judgment may need to be referred to an appropriately qualified professional.</p></div></section></main><Footer /></div>;
}
