export interface FreeResourceLeadDefinition {
  slug: string;
  name: string;
  category: string;
  format: "Fillable PDF" | "Spreadsheet";
  interest: string;
  interestSlug: string;
  primaryPaidOffer: string;
  primaryPaidOfferSlug: string | null;
  secondaryPaidOffer: string | null;
  secondaryPaidOfferSlug: string | null;
  downloadPath: string;
  filename: string;
  resourceHelpText: string;
  gettingStartedTip: string;
}

export const FREE_RESOURCE_LEAD_REGISTRY: readonly FreeResourceLeadDefinition[] = [
  { slug: "30-minute-business-reset", name: "30-Minute Business Reset", category: "Business Foundations", format: "Fillable PDF", interest: "Business Foundations", interestSlug: "business-foundations", primaryPaidOffer: "Professional Systems™ / diagnosed system", primaryPaidOfferSlug: "business-bloom-professional-systems", secondaryPaidOffer: "Operations System™", secondaryPaidOfferSlug: "business-bloom-operations-system", downloadPath: "/downloads/free-resources/Business-Bloom-30-Minute-Business-Reset-Fillable.pdf", filename: "Business-Bloom-30-Minute-Business-Reset-Fillable.pdf", resourceHelpText: "Use this focused reset to identify the business issue that needs attention first and choose a practical next action.", gettingStartedTip: "Name the single issue creating the most drag, then choose one action you can complete next." },
  { slug: "business-systems-checklist", name: "Business Systems Checklist", category: "Operations / Systems", format: "Fillable PDF", interest: "Operations / Systems", interestSlug: "operations-systems", primaryPaidOffer: "Operations System™", primaryPaidOfferSlug: "business-bloom-operations-system", secondaryPaidOffer: "Professional Systems™", secondaryPaidOfferSlug: "business-bloom-professional-systems", downloadPath: "/downloads/free-resources/Business-Bloom-Business-Systems-Checklist-Fillable.pdf", filename: "Business-Bloom-Business-Systems-Checklist-Fillable.pdf", resourceHelpText: "Review the systems your business relies on and spot where missing or inconsistent processes may be creating avoidable friction.", gettingStartedTip: "Mark the weakest areas today, then pick one process to document or improve first." },
  { slug: "business-health-check", name: "Business Health Check", category: "Business Foundations", format: "Spreadsheet", interest: "Business Foundations", interestSlug: "business-foundations", primaryPaidOffer: "Professional Systems™", primaryPaidOfferSlug: "business-bloom-professional-systems", secondaryPaidOffer: "Most relevant diagnosed system", secondaryPaidOfferSlug: null, downloadPath: "/api/free-resources/business-health-check", filename: "Business-Bloom-Business-Health-Check.xlsx", resourceHelpText: "Assess key areas of your business so you can see where stronger systems or follow-through may be needed.", gettingStartedTip: "Complete the check once without overthinking it, then focus on the lowest-scoring area." },
  { slug: "customer-service-scorecard", name: "Customer Service Scorecard", category: "Customer Service", format: "Spreadsheet", interest: "Customer Service", interestSlug: "customer-service", primaryPaidOffer: "Customer Service System™", primaryPaidOfferSlug: "business-bloom-customer-service-system", secondaryPaidOffer: null, secondaryPaidOfferSlug: null, downloadPath: "/downloads/free-resources/Business-Bloom-Customer-Service-Scorecard.xlsx", filename: "Business-Bloom-Customer-Service-Scorecard.xlsx", resourceHelpText: "Evaluate customer-service consistency and identify where response, resolution, escalation, or follow-up can improve.", gettingStartedTip: "Score the experience as it operates today, then choose the weakest service area for one improvement." },
  { slug: "sales-conversion-calculator", name: "Sales Conversion Calculator", category: "Sales", format: "Spreadsheet", interest: "Sales", interestSlug: "sales", primaryPaidOffer: "Sales System™", primaryPaidOfferSlug: "business-bloom-sales-system", secondaryPaidOffer: null, secondaryPaidOfferSlug: null, downloadPath: "/downloads/free-resources/Business-Bloom-Sales-Conversion-Calculator.xlsx", filename: "Business-Bloom-Sales-Conversion-Calculator.xlsx", resourceHelpText: "Turn basic sales activity into clearer conversion visibility so you can spot where opportunities are being lost.", gettingStartedTip: "Enter real lead and sales numbers first, then look for the stage with the largest drop-off." },
  { slug: "interview-scorecard", name: "Interview Scorecard", category: "HR", format: "Spreadsheet", interest: "HR", interestSlug: "hr", primaryPaidOffer: "HR System™", primaryPaidOfferSlug: "business-bloom-hr-system", secondaryPaidOffer: null, secondaryPaidOfferSlug: null, downloadPath: "/downloads/free-resources/Business-Bloom-Interview-Scorecard.xlsx", filename: "Business-Bloom-Interview-Scorecard.xlsx", resourceHelpText: "Compare candidates against consistent job-related criteria instead of relying only on memory or first impressions.", gettingStartedTip: "Define the role criteria before the interview, then score each candidate against the same factors." },
  { slug: "marketing-roi-calculator", name: "Marketing ROI Calculator", category: "Marketing", format: "Spreadsheet", interest: "Marketing", interestSlug: "marketing", primaryPaidOffer: "Marketing System™", primaryPaidOfferSlug: "business-bloom-marketing-system", secondaryPaidOffer: null, secondaryPaidOfferSlug: null, downloadPath: "/api/free-resources/marketing-roi-calculator", filename: "Business-Bloom-Marketing-ROI-Calculator.xlsx", resourceHelpText: "Compare marketing spend with attributable return so you can evaluate campaign performance more clearly.", gettingStartedTip: "Start with one campaign and use the best available actual cost and return figures." },
  { slug: "website-conversion-checklist", name: "Website Conversion Checklist", category: "Website / Conversion", format: "Fillable PDF", interest: "Website / Conversion", interestSlug: "website-conversion", primaryPaidOffer: "Website System", primaryPaidOfferSlug: "business-bloom-website-system", secondaryPaidOffer: "Content Marketing System", secondaryPaidOfferSlug: "business-bloom-content-marketing-system", downloadPath: "/downloads/free-resources/Business-Bloom-Website-Conversion-Checklist-Fillable.pdf", filename: "Business-Bloom-Website-Conversion-Checklist-Fillable.pdf", resourceHelpText: "Review an important website page for clarity, focus, trust, and call-to-action strength, then identify the highest-impact fix.", gettingStartedTip: "Choose one high-value page and complete the checklist for that page before changing anything else." },
  { slug: "social-content-consistency-planner", name: "Social Content Consistency Planner", category: "Social Media / Content", format: "Spreadsheet", interest: "Social Media / Content", interestSlug: "social-media-content", primaryPaidOffer: "Social Media System", primaryPaidOfferSlug: "business-bloom-social-media-system", secondaryPaidOffer: "Content Marketing System", secondaryPaidOfferSlug: "business-bloom-content-marketing-system", downloadPath: "/downloads/free-resources/Business-Bloom-Social-Content-Consistency-Planner.xlsx", filename: "Business-Bloom-Social-Content-Consistency-Planner.xlsx", resourceHelpText: "Plan a practical week of social content around audience problems, useful formats, clear hooks, and next actions.", gettingStartedTip: "Plan one complete week first and make each post useful to a specific audience problem." },
  { slug: "brand-message-quick-check", name: "Brand Message Quick Check", category: "Branding / Messaging", format: "Fillable PDF", interest: "Branding / Messaging", interestSlug: "branding-messaging", primaryPaidOffer: "Branding System", primaryPaidOfferSlug: "business-bloom-branding-system", secondaryPaidOffer: "Marketing System™", secondaryPaidOfferSlug: "business-bloom-marketing-system", downloadPath: "/downloads/free-resources/Business-Bloom-Brand-Message-Quick-Check-Fillable.pdf", filename: "Business-Bloom-Brand-Message-Quick-Check-Fillable.pdf", resourceHelpText: "Clarify who you help, what you help them achieve, and why the message should matter to the customer.", gettingStartedTip: "Write your current message as customers see it, then tighten the audience, outcome, and reason to care." },
  { slug: "sop-quick-start-template", name: "SOP Quick-Start Template", category: "Operations / Systems", format: "Spreadsheet", interest: "Operations / Systems", interestSlug: "operations-systems", primaryPaidOffer: "Operations System™", primaryPaidOfferSlug: "business-bloom-operations-system", secondaryPaidOffer: null, secondaryPaidOfferSlug: null, downloadPath: "/downloads/free-resources/Business-Bloom-SOP-Quick-Start-Template.xlsx", filename: "Business-Bloom-SOP-Quick-Start-Template.xlsx", resourceHelpText: "Turn one recurring task into a clearer repeatable process with steps, ownership, and practical operating detail.", gettingStartedTip: "Pick a task that happens often and document how it is actually done before trying to optimize it." },
  { slug: "ai-automation-opportunity-finder", name: "AI Automation Opportunity Finder", category: "AI / Automation", format: "Spreadsheet", interest: "AI / Automation", interestSlug: "ai-automation", primaryPaidOffer: "AI Automation Bundles™", primaryPaidOfferSlug: "business-bloom-ai-automation-bundles", secondaryPaidOffer: "Operations System™", secondaryPaidOfferSlug: "business-bloom-operations-system", downloadPath: "/downloads/free-resources/Business-Bloom-AI-Automation-Opportunity-Finder.xlsx", filename: "Business-Bloom-AI-Automation-Opportunity-Finder.xlsx", resourceHelpText: "Identify repetitive work that may be worth evaluating for practical, human-reviewed AI or automation support.", gettingStartedTip: "Start with repetitive, rules-based work, then evaluate value, feasibility, and needed human review." },
  { slug: "weekly-ceo-priority-planner", name: "Weekly CEO Priority Planner", category: "Productivity / Executive Planning", format: "Fillable PDF", interest: "Productivity / Executive Planning", interestSlug: "productivity-executive-planning", primaryPaidOffer: "Professional Systems™", primaryPaidOfferSlug: "business-bloom-professional-systems", secondaryPaidOffer: "Operations System™", secondaryPaidOfferSlug: "business-bloom-operations-system", downloadPath: "/downloads/free-resources/Business-Bloom-Weekly-CEO-Priority-Planner.pdf", filename: "Business-Bloom-Weekly-CEO-Priority-Planner.pdf", resourceHelpText: "Focus the week on one primary outcome, three priorities, accountable actions, blockers, decisions, and a short end-of-week review.", gettingStartedTip: "Choose this week’s primary outcome first, then schedule the first priority before adding lower-value tasks." },
] as const;

const BY_SLUG = new Map(FREE_RESOURCE_LEAD_REGISTRY.map((resource) => [resource.slug, resource]));
export function getFreeResourceLeadDefinition(slug: string) { return BY_SLUG.get(slug) ?? null; }
