export interface PublicMarketplaceProduct {
  slug: string;
  name: string;
  collection: string;
  shortDescription: string;
  category: string;
  type: "system" | "bundle";
  benefits: string[];
  included: string[];
  fulfillmentType: "download" | "access" | "onboarding" | "hybrid";
}

/** Browser-safe public catalog projection. Never add private source IDs or internal fulfillment data. */
export const PUBLIC_MARKETPLACE_PRODUCTS: PublicMarketplaceProduct[] = [
  {
    slug: "business-bloom-customer-service-system",
    name: "Business Bloom Customer Service System™",
    collection: "Customer experience and service operations",
    shortDescription: "A practical customer-service system for turning inconsistent responses and follow-up into documented service standards, escalation steps, and repeatable customer-care workflows.",
    category: "Professional Systems",
    type: "system",
    benefits: [
      "Set clearer service and response expectations",
      "Give team members a repeatable way to handle common customer situations",
      "Organize escalation and follow-up so issues are less likely to fall through the cracks",
      "Track service quality and identify areas to improve",
    ],
    included: [
      "Customer service guides and documents — help you define standards, response expectations, follow-up, and escalation practices.",
      "Interactive tools — help you evaluate service quality and turn observations into next actions.",
      "Implementation resources — help you put the system into day-to-day use instead of leaving it as reference material.",
      "Organized digital package — keeps the customer-facing materials together for practical use.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-hr-system",
    name: "Business Bloom HR System™",
    collection: "Hiring, onboarding, and people operations",
    shortDescription: "A structured HR system for owners and managers who want a more consistent way to hire, onboard, document, develop, and manage people without recreating the process each time.",
    category: "Professional Systems",
    type: "system",
    benefits: [
      "Build a repeatable hiring and onboarding process",
      "Organize employee documentation and manager follow-up",
      "Use structured tools for interviews, performance conversations, and people-management tasks",
      "Create more consistency across managers while preserving professional-review boundaries",
    ],
    included: [
      "HR operating materials — help you organize core hiring, onboarding, documentation, and performance workflows.",
      "Reusable customer documents — give you starting points for recurring people-management activities.",
      "Interactive tools — help managers evaluate information and document next steps more consistently.",
      "Organized digital package — keeps the system materials together for practical implementation.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-marketing-system",
    name: "Business Bloom Marketing System™",
    collection: "Marketing strategy and campaign execution",
    shortDescription: "A practical marketing system that helps you clarify your audience and message, plan campaigns and promotions, and turn scattered marketing activity into a repeatable execution process.",
    category: "Professional Systems",
    type: "system",
    benefits: [
      "Clarify who you are marketing to and what you want them to understand",
      "Plan campaigns and promotions before execution begins",
      "Create a repeatable marketing rhythm instead of starting from scratch",
      "Use AI prompts intentionally to support planning, review, and execution",
    ],
    included: [
      "Marketing Quick Start Guide — shows you where to begin and how to move through the system.",
      "Marketing Strategy Playbook and Toolkit — helps you organize audience, positioning, messaging, objectives, and execution choices.",
      "Marketing Campaign Toolkit — helps you structure campaigns, promotions, channels, and next actions before launch.",
      "Fillable Interactive Toolkit — gives you practical places to capture decisions and turn strategy into usable plans.",
      "Marketing AI Prompt Library — provides guided prompts for planning, analysis, refinement, and marketing execution with human review.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-operations-system",
    name: "Business Bloom Operations System™",
    collection: "SOPs, workflows, and day-to-day execution",
    shortDescription: "An operations system that helps you move important processes out of your head and into documented workflows, SOPs, responsibilities, dashboards, and repeatable operating routines.",
    category: "Professional Systems",
    type: "system",
    benefits: [
      "Document recurring work so it can be repeated more consistently",
      "Clarify roles, handoffs, responsibilities, and process ownership",
      "Identify bottlenecks and improvement opportunities in day-to-day workflows",
      "Track implementation and recurring operations from a more organized system",
    ],
    included: [
      "Operations Quick Start Guide — shows you how to begin documenting and improving the work that matters most.",
      "Operations Playbook and Toolkit — helps you organize workflows, responsibilities, recurring operations, and process-improvement decisions.",
      "Operations SOP Toolkit — provides a repeatable way to turn recurring tasks into usable standard operating procedures.",
      "Fillable Interactive Toolkit — helps you capture operational decisions, owners, priorities, and next steps.",
      "Operations AI Prompt Library — provides guided prompts for drafting, reviewing, and improving operational processes with human review.",
      "Operations Quick Reference — gives you a fast reminder of the system and where to focus next.",
      "Operations Management Dashboard — provides one place to organize implementation and operating priorities.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-ai-automation-bundles",
    name: "Business Bloom AI Automation Bundles™",
    collection: "Practical AI and automation implementation",
    shortDescription: "A practical AI and automation system for identifying repetitive work, designing human-reviewed workflows, and turning useful AI ideas into structured business processes instead of isolated experiments.",
    category: "Professional Systems",
    type: "system",
    benefits: [
      "Identify repetitive work that may be suitable for AI or automation",
      "Design workflows with clear human-review and control points",
      "Reuse prompts and planning frameworks instead of improvising every task",
      "Prioritize automation ideas by business value, feasibility, and risk",
    ],
    included: [
      "AI Automation Quick Start — helps you choose a practical starting point without trying to automate everything at once.",
      "AI Automation Playbook — gives you a structured approach for evaluating, planning, and reviewing AI-assisted work.",
      "AI Automation Design Toolkit — helps you map workflows, inputs, outputs, controls, and human-review points.",
      "Fillable Interactive Toolkit — gives you practical places to capture automation decisions and implementation notes.",
      "AI Automation Prompt Library — provides reusable prompts for analysis, planning, drafting, and review without promising autonomous results.",
      "AI Automation Quick Reference — helps you quickly remember the core process and safeguards.",
      "Automation Opportunity Dashboard — gives you one place to organize candidate automations, priorities, and progress.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-professional-systems",
    name: "Business Bloom Professional Systems™",
    collection: "Six coordinated business systems plus implementation toolkit",
    shortDescription: "A coordinated business operating framework that brings together six complete Business Bloom systems—Customer Service, HR, Marketing, Operations, AI Automation, and Sales—plus tools to help you implement them as one connected system.",
    category: "Professional Systems",
    type: "bundle",
    benefits: [
      "Build core business functions from coordinated systems instead of disconnected files",
      "Create more consistency across service, people, marketing, operations, automation, and sales",
      "Use one implementation framework to decide what to tackle first",
      "Track progress across the included systems from a shared dashboard",
    ],
    included: [
      "Six complete Business Bloom business systems — Customer Service, HR, Marketing, Operations, AI Automation, and Sales.",
      "Professional Systems Start Here Guide — shows you where to begin and how to approach implementation across the bundle.",
      "Customer Use Framework — helps you turn the materials into an operating system rather than a collection of unused files.",
      "Professional Systems Dashboard — provides one place to track implementation progress across the included systems.",
      "Organized digital package — keeps the customer-facing system resources and implementation materials together.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-website-system",
    name: "Business Bloom Website System",
    collection: "Website strategy, content, workflow, and launch QA",
    shortDescription: "A structured website-planning and operations system for business owners who want a clearer way to plan pages, develop messaging, organize website work, review quality, and improve the site over time.",
    category: "Digital Business",
    type: "system",
    benefits: [
      "Plan website strategy and page priorities before building page by page",
      "Develop clearer website messaging and content with guided prompts and worksheets",
      "Move website work through repeatable planning, review, and launch workflows",
      "Use examples and QA tools to review quality before publishing changes",
    ],
    included: [
      "Customer guides — explain how to plan, organize, and use the website system from strategy through ongoing operations.",
      "Prompt library — gives you guided prompts for page planning, messaging, content review, troubleshooting, and website decisions.",
      "Workflows — provide repeatable processes for moving website work from idea through review and implementation.",
      "Worksheets and templates — help you organize decisions, page requirements, content, and next actions.",
      "Examples — show how the frameworks can be applied so you do not have to begin from a blank page.",
      "Quality and safety materials — help you review content, claims, usability, and launch-readiness considerations before publishing.",
      "Quick reference — gives you a fast reminder of the process when you need the next step.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-virtual-executive-team",
    name: "Business Bloom Virtual Executive Team™",
    collection: "AI-assisted executive decision support",
    shortDescription: "Executive-level business decision support for entrepreneurs who do not have a full C-suite sitting around the conference table. Use structured CEO, CFO, COO, and CMO perspectives to examine strategy, money, operations, customers, and execution before you make the final call.",
    category: "Executive",
    type: "system",
    benefits: [
      "Examine important decisions from multiple executive perspectives",
      "Identify strategic, financial, marketing, and operational tradeoffs you may not have considered",
      "Document competing recommendations before choosing a direction",
      "Turn an owner-approved decision into a practical action plan",
      "Create a repeatable executive-review process for future business issues",
    ],
    included: [
      "Your Virtual Executive Team — dedicated CEO, CFO, COO, and CMO role instructions that help AI respond from distinct leadership perspectives rather than one generic viewpoint.",
      "Executive Decision Questionnaire — helps you define the decision, context, constraints, and goals before asking the team to weigh in.",
      "Executive Team Prompt Library — guided prompts for business intake, coordinated executive review, synthesis, planning, and recurring decision review.",
      "Start Here Guide and Customer Guide — show you how to set up the system and work with the executive perspectives effectively and responsibly.",
      "Intake Workbook — helps organize the business information your virtual executives need before analyzing a decision.",
      "Decision-support workflows — provide repeatable processes for strategic decisions, leadership reviews, planning, and follow-through.",
      "Worksheets and templates — help capture recommendations, tradeoffs, decisions, priorities, and follow-up actions.",
      "Examples and Quick Reference — show realistic uses and help you quickly choose the right executive perspective and review process.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-branding-system",
    name: "Business Bloom Branding System",
    collection: "Brand foundation, positioning, and consistency",
    shortDescription: "A practical branding system for business owners who want to make deliberate decisions about positioning, identity, messaging, and consistency instead of choosing brand elements randomly.",
    category: "Startup",
    type: "system",
    benefits: [
      "Clarify the foundation and positioning behind your brand",
      "Make more consistent decisions about messaging and visual direction",
      "Use editable resources and worksheets to document brand choices",
      "Apply practical examples and references when refining the brand",
    ],
    included: [
      "Core editable resources — give you practical starting materials for documenting and applying brand decisions.",
      "Brand worksheets — guide you through positioning, messaging, identity, and consistency decisions.",
      "Examples and reference materials — show how the frameworks can be applied and give you practical points of comparison.",
      "Customer PDFs — provide ready-to-use guidance and reference material for implementing the system.",
      "Organized digital package — brings the customer-facing branding resources together for practical use.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-foundation-system",
    name: "Business Bloom LLC Foundation System",
    collection: "Business setup planning and organization",
    shortDescription: "An educational business-foundation system that helps entrepreneurs organize formation planning, filing preparation, startup information, documentation, and next steps before completing or reviewing jurisdiction-specific requirements.",
    category: "Startup",
    type: "system",
    benefits: [
      "Organize the information needed for business-setup planning",
      "Prepare more systematically for filing and startup tasks",
      "Keep foundational business information and next steps in one process",
      "Identify decisions that should be reviewed by qualified legal, tax, or other professionals",
    ],
    included: [
      "Business-foundation materials — help you organize core startup information, planning, and documentation.",
      "Implementation resources — give you a practical sequence for moving through setup tasks and tracking next actions.",
      "Professional-review guidance — highlights areas where legal, tax, filing, licensing, or jurisdiction-specific review may be appropriate.",
      "Organized digital package — keeps the customer-facing foundation materials together for practical use.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-business-launch-blueprint",
    name: "Business Bloom Business Launch Blueprint",
    collection: "Idea-to-launch planning and execution",
    shortDescription: "A practical launch-planning system for entrepreneurs who need a clearer sequence for turning an idea into an organized offer, setup plan, marketing preparation, launch checklist, and first implementation period.",
    category: "Startup",
    type: "system",
    benefits: [
      "Decide what to do first, second, and next instead of trying to launch everything at once",
      "Organize offer, setup, and marketing preparation into one launch path",
      "Turn launch ideas into priorities, checklists, and implementation actions",
      "Create a repeatable structure for reviewing launch readiness and next steps",
    ],
    included: [
      "Launch-planning materials — help you organize the offer, priorities, setup work, and launch sequence.",
      "Implementation resources — turn launch decisions into practical actions and a manageable order of work.",
      "Quick-reference materials — help you keep the next priority visible as you move toward launch.",
      "Organized digital package — brings the customer-facing launch resources together for practical use.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-content-marketing-system",
    name: "Business Bloom Content Marketing System",
    collection: "Content strategy, production, repurposing, and measurement",
    shortDescription: "A repeatable content-marketing system for business owners who are tired of wondering what to create and want a clearer process for planning, producing, repurposing, publishing, and reviewing content.",
    category: "Marketing",
    type: "system",
    benefits: [
      "Define content priorities and recurring themes before you start creating",
      "Move ideas through a repeatable creation and publishing workflow",
      "Repurpose useful ideas instead of rebuilding every piece from scratch",
      "Review performance and use what you learn to improve future content decisions",
    ],
    included: [
      "Customer guides — help you organize content strategy, planning, production, publishing, and review.",
      "Prompt library — provides guided prompts for ideation, drafting, repurposing, refinement, and content review with human oversight.",
      "Workflows — give you repeatable processes for moving content from idea to publication and reuse.",
      "Worksheets and templates — help you document themes, plans, content decisions, and next actions.",
      "Examples — show how the frameworks can be applied instead of forcing you to start from a blank page.",
      "Quality and safety materials — support responsible review of claims, accuracy, and publishing decisions.",
      "Quick reference — helps you quickly identify the next step in the content process.",
    ],
    fulfillmentType: "download",
  },
  {
    slug: "business-bloom-social-media-system",
    name: "Business Bloom Social Media System",
    collection: "Social strategy, planning, publishing, and performance review",
    shortDescription: "A practical social-media system for business owners who are tired of posting randomly and want a repeatable process for planning content, coordinating campaigns, publishing consistently, and reviewing what is working.",
    category: "Marketing",
    type: "system",
    benefits: [
      "Plan social content before the week begins",
      "Organize campaigns, recurring themes, and publishing priorities",
      "Move content through a repeatable creation and publishing workflow",
      "Reduce last-minute posting by documenting the process",
      "Review performance and improve future social-media decisions",
    ],
    included: [
      "Planning resources — help you organize themes, campaigns, posting priorities, and content ideas before creation begins.",
      "Publishing workflows — provide a repeatable process for moving content from idea to creation, review, scheduling, and publication.",
      "Examples and reference materials — show how the system can be applied and give you practical starting points.",
      "Organized digital package — keeps the customer-facing social-media resources together for consistent use.",
    ],
    fulfillmentType: "download",
  },
];

export const PUBLIC_FREE_RESOURCES = [
  { slug: "30-minute-business-reset", name: "30-Minute Business Reset", category: "Business Foundations", format: "Fillable PDF" },
  { slug: "business-systems-checklist", name: "Business Systems Checklist", category: "Business Foundations", format: "Fillable PDF" },
  { slug: "business-health-check", name: "Business Health Check", category: "Business Foundations", format: "Spreadsheet" },
] as const;

export function getPublicMarketplaceProduct(slug: string) {
  return PUBLIC_MARKETPLACE_PRODUCTS.find((product) => product.slug === slug) ?? null;
}
